In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
#df_category_links = pd.read_csv("/content/categorylinks.csv") # PUEDE SER 
#df_contents = pd.read_csv("/content/contents.csv")  # PUEDE SER 
df_logs = pd.read_csv("/content/drive/MyDrive/Organizacion De Datos/Trabajo_practico/logs.csv")  # TIENE QUE SER ESTE
#df_contents_text_sample = pd.read_csv("/content/contents_text_sample.csv") # NO ABRE

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<ipython-input-1-50be734ebb28>:6: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_logs = pd.read_csv("/content/drive/MyDrive/Organizacion De Datos/Trabajo_practico/logs.csv")  # TIENE QUE SER ESTE

In [2]:
#df_logs.head()

In [3]:
#df_logs.info()

In [4]:
df_logs_limpio = df_logs # copio para evitar el warning del .loc      
df_logs_limpio

,item_id,timestamp,contributor_username,contributor_id,contributor_ip,comment,logtype,action,title
0,1,2004-12-23T07:10:09Z,Sabbut,2075.0,NaN,el contenido era: 'Si aprendés Pensamiento Cie...,delete,delete,Verificacionismo
1,2,2004-12-23T07:14:09Z,Sabbut,2075.0,NaN,el contenido era: '{{destruir}}en algun lugar ...,delete,delete,Rapunzel
2,3,2004-12-23T07:26:10Z,Sabbut,2075.0,NaN,el contenido era: '#REDIRECT [[Flash]]',delete,delete,Macromedia Flash
3,4,2004-12-23T07:55:09Z,Sanbec,7856.0,NaN,Sin información de origen ni de licencia. Hay ...,delete,delete,Archivo:Gnu head.png
4,5,2004-12-23T08:02:22Z,Sanbec,7856.0,NaN,Sustituida por [[commons:Image:Heckert_GNU.png]],delete,delete,Archivo:Gnu-head-sm.jpg
...,...,...,...,...,...,...,...,...,...
12188941,15587395,2021-09-03T03:09:13Z,SeroBOT,4980693.0,NaN,Aviso de pruebas a usuario tras reversiones co...,create,create,Usuario discusión:El guachicol
12188942,15587396,2021-09-03T03:09:48Z,Leonpolanco,561850.0,NaN,Página creada con «{{subst:Aviso prueba2|Luis ...,create,create,Usuario discusión:2806:2F0:3140:BE0:C09B:D1C4:...
12188943,15587397,2021-09-03T03:09:49Z,Desiretjs,6335019.0,NaN,NaN,newusers,create,Usuario:Desiretjs
12188944,15587398,2021-09-03T03:10:33Z,Correogsk,443260.0,NaN,Página redirigida a [[Contenedor]],create,create,Contenedores
12188945,15587399,2021-09-03T03:10:38Z,Liza.amane,6335020.0,NaN,NaN,newusers,create,Usuario:Liza.amane

In [5]:
df_logs_limpio["timestamp"] = pd.to_datetime(df_logs_limpio["timestamp"]).dt.date # paso la fecha a objeto fecha con datetime y dt.date para que me saque la hora
df_logs_limpio

,item_id,timestamp,contributor_username,contributor_id,contributor_ip,comment,logtype,action,title
0,1,2004-12-23,Sabbut,2075.0,NaN,el contenido era: 'Si aprendés Pensamiento Cie...,delete,delete,Verificacionismo
1,2,2004-12-23,Sabbut,2075.0,NaN,el contenido era: '{{destruir}}en algun lugar ...,delete,delete,Rapunzel
2,3,2004-12-23,Sabbut,2075.0,NaN,el contenido era: '#REDIRECT [[Flash]]',delete,delete,Macromedia Flash
3,4,2004-12-23,Sanbec,7856.0,NaN,Sin información de origen ni de licencia. Hay ...,delete,delete,Archivo:Gnu head.png
4,5,2004-12-23,Sanbec,7856.0,NaN,Sustituida por [[commons:Image:Heckert_GNU.png]],delete,delete,Archivo:Gnu-head-sm.jpg
...,...,...,...,...,...,...,...,...,...
12188941,15587395,2021-09-03,SeroBOT,4980693.0,NaN,Aviso de pruebas a usuario tras reversiones co...,create,create,Usuario discusión:El guachicol
12188942,15587396,2021-09-03,Leonpolanco,561850.0,NaN,Página creada con «{{subst:Aviso prueba2|Luis ...,create,create,Usuario discusión:2806:2F0:3140:BE0:C09B:D1C4:...
12188943,15587397,2021-09-03,Desiretjs,6335019.0,NaN,NaN,newusers,create,Usuario:Desiretjs
12188944,15587398,2021-09-03,Correogsk,443260.0,NaN,Página redirigida a [[Contenedor]],create,create,Contenedores
12188945,15587399,2021-09-03,Liza.amane,6335020.0,NaN,NaN,newusers,create,Usuario:Liza.amane

In [6]:
# me quedo con los datos que me interesan
#df_logs_limpio.loc[:,"actividades"] = 0
df_logs_limpio = df_logs_limpio[ ["timestamp"] ]

In [7]:
df_logs_limpio

           timestamp
0         2004-12-23
1         2004-12-23
2         2004-12-23
3         2004-12-23
4         2004-12-23
...              ...
12188941  2021-09-03
12188942  2021-09-03
12188943  2021-09-03
12188944  2021-09-03
12188945  2021-09-03

[12188946 rows x 1 columns]

In [14]:
agrupado_fechas = df_logs_limpio.groupby("timestamp").agg({"timestamp":["count"]})
agrupado_fechas = agrupado_fechas.reset_index()
agrupado_fechas

       timestamp
                 count
0     2004-12-23    91
1     2004-12-24    36
2     2004-12-25    43
3     2004-12-26    45
4     2004-12-27    98
...          ...   ...
6094  2021-08-30  2416
6095  2021-08-31  2208
6096  2021-09-01  2289
6097  2021-09-02  2306
6098  2021-09-03   312

[6099 rows x 2 columns]

In [15]:
agrupado_fechas.columns = ["fecha","actividades"]
agrupado_fechas

           fecha  actividades
0     2004-12-23           91
1     2004-12-24           36
2     2004-12-25           43
3     2004-12-26           45
4     2004-12-27           98
...          ...          ...
6094  2021-08-30         2416
6095  2021-08-31         2208
6096  2021-09-01         2289
6097  2021-09-02         2306
6098  2021-09-03          312

[6099 rows x 2 columns]

In [21]:
# filtrar con loc para ver que no se repita el maximo y el minimo (ya está hecho)
maxima_cantidad = agrupado_fechas.actividades.max()
minima_cantidad = agrupado_fechas.actividades.min()

agrupado_fechas["maximo"] = agrupado_fechas["actividades"] >= maxima_cantidad
agrupado_fechas["minimo"] = agrupado_fechas["actividades"] <= minima_cantidad
agrupado_fechas.head()

        fecha  actividades  maximo  minimo
0  2004-12-23           91   False   False
1  2004-12-24           36   False   False
2  2004-12-25           43   False   False
3  2004-12-26           45   False   False
4  2004-12-27           98   False   False

In [22]:
agrupado_fechas[ agrupado_fechas["maximo"] ] #muestra las filas cuya actividad son mayores o iguales a la maxima

           fecha  actividades  maximo  minimo
3769  2015-04-19       390863    True   False

In [23]:
agrupado_fechas[ agrupado_fechas["minimo"] ]    #muestra las filas cuya actividad son mayores o iguales a la minimia

         fecha  actividades  maximo  minimo
61  2005-02-22            4   False    True

In [24]:
agrupado_fechas["fecha"][agrupado_fechas["maximo"]] #asi me muestra todas las fechas que tienen true en maximo (respuesta que me piden, ya está bien asi)

3769    2015-04-19
Name: fecha, dtype: object

In [26]:
agrupado_fechas["fecha"][agrupado_fechas["minimo"]] #asi me muestra todas las fechas que tienen true en minimo (respuesta que me piden, ya está bien asi)

61    2005-02-22
Name: fecha, dtype: object