In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_languages = pd.read_csv("/content/drive/MyDrive/Organizacion De Datos/Trabajo_practico/languages.csv")
#Si decimos que un usuario sabe un idioma cuando tiene un nivel de babel mayor o igual a 1, para aquellos que editaron una de las versiones actuales del contenido, 
#¿Cuál es la tasa de revisiones sin comentario que realizan en función de los idiomas que saben? (⭐⭐⭐)

In [ ]:
df_contenidos = pd.read_csv("/content/drive/MyDrive/Organizacion De Datos/Trabajo_practico/contents.csv")

In [ ]:
df_languages.head()

   babel_user babel_lang babel_level
0     4502458         FR           2
1     5928200         aa           0
2       46918         ab           0
3     2050449         ab           1
4     4715583        ace           0

In [ ]:
df_languages = df_languages[df_languages['babel_level'] != '0']
df_languages.head()

   babel_user babel_lang babel_level
0     4502458         FR           2
3     2050449         ab           1
6     4494742        acf           1
8       70090         af           1
9      407454         af           1

In [ ]:
df_contenidos.head()

,title,id,namespace,revision_id,parent_revision,revision_timestamp,revisor_username,revisor_id,revisor_ip,revisor_comment
0,Wikipedia:Artículos solicitados,5,4,132533307,132516631.0,2021-01-19T18:40:34Z,Metrónomo,1708233.0,NaN,Así esta mejor
1,Andorra,7,0,138035057,138027475.0,2021-08-31T18:27:01Z,NaN,NaN,2800:CD0:FC1B:A900:C5A4:9E81:7175:2ED2,Añadir contenido
2,Argentina,10,0,137966826,137825165.0,2021-08-28T17:17:54Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...
3,Geografía de Andorra,15,0,137986788,133666383.0,2021-08-29T17:16:00Z,Lojwe,5338508.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...
4,Demografía de Andorra,17,0,130869554,129413188.0,2020-11-12T19:56:15Z,Jialxv,3615366.0,NaN,Correcciones ortográficas con [[Usuario:Benjav...

In [ ]:
df_languages.rename(columns = {'babel_user':'revisor_id'}, inplace = True)

In [ ]:
nuevo_df = pd.merge(df_contenidos, df_languages, how="inner")

In [ ]:
nuevo_df.info()

In [ ]:
nuevo_df.babel_level.unique()

In [ ]:
nuevo_df

,title,id,namespace,revision_id,parent_revision,revision_timestamp,revisor_username,revisor_id,revisor_ip,revisor_comment,babel_lang,babel_level
0,Argentina,10,0,137966826,137825165.0,2021-08-28T17:17:54Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,de,N
1,Argentina,10,0,137966826,137825165.0,2021-08-28T17:17:54Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,en,4
2,Argentina,10,0,137966826,137825165.0,2021-08-28T17:17:54Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,es,N
3,Argentina,10,0,137966826,137825165.0,2021-08-28T17:17:54Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,fr,2
4,Argentina,10,0,137966826,137825165.0,2021-08-28T17:17:54Z,Traitrich,4642283.0,NaN,Reemplazos con [[Usuario:Benjavalero/Replacer|...,ru,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3281466,Copa Italia 2021-22,9995136,0,137726316,137726302.0,2021-08-17T12:52:00Z,Dr Salvus,5913066.0,NaN,/* Rondas eliminatorias */,it,N
3281467,Miharu Koshi,10004261,0,138031666,138021121.0,2021-08-31T15:57:35Z,Alejofon27,3977113.0,NaN,NaN,de,2
3281468,Miharu Koshi,10004261,0,138031666,138021121.0,2021-08-31T15:57:35Z,Alejofon27,3977113.0,NaN,NaN,en,4
3281469,Miharu Koshi,10004261,0,138031666,138021121.0,2021-08-31T15:57:35Z,Alejofon27,3977113.0,NaN,NaN,es,N
3281470,Miharu Koshi,10004261,0,138031666,138021121.0,2021-08-31T15:57:35Z,Alejofon27,3977113.0,NaN,NaN,ja,2

In [ ]:
agrupado = nuevo_df.groupby("babel_level").agg({"babel_level":["count"], "revisor_comment":["count"]})

In [ ]:
agrupado.columns = ["total_usuarios","con_comentarios"]

In [ ]:
agrupado["sin_comentario"] = (agrupado.total_usuarios - agrupado.con_comentarios)

In [ ]:
agrupado

In [ ]:
agrupado["tasa_revisiones_sin_comentario"] = (agrupado.sin_comentario / agrupado.total_usuarios) *100

la tasa de revisiones sin comentario que realizan en función de los idiomas que saben es la siguiente:

In [ ]:
agrupado[["tasa_revisiones_sin_comentario"]]

             tasa_revisiones_sin_comentario
babel_level
1                                 13.951211
2                                 11.227877
3                                 13.181830
4                                 13.318133
5                                 43.935339
N                                 14.417081